parallaxsecond/parsec-client-rust

.github/workflows/ci.yml, .gitignore, .travis.yml, CONTRIBUTING.md, Cargo.toml, DCO.txt, LICENSE, MAINTAINERS.toml, README.md, src/auth.rs, src/core/mod.rs, src/core/operation_handler.rs, src/core/request_handler.rs, src/lib.rs, tests/ci.sh
This commit adds the initial version of the Parsec Rust client.
This version of the client is *not* finished and requires a lot of changes for it to be usable/production-ready. Some of the things that are not done well and will be improved are:
* documentation is minimal and needs to be expanded
* tests should be implemented, either with a "mock service" or with the real Parsec service
* there are still unsafe uses of `unwrap`, `expect` ...
* there is no configuration of the parameters used
* the API of the client was not designed to match any existing "ergonomic design" crypto APIs from the Rust ecosystem
* potentially others - if you find this kind of issues that are more structural than syntactic/aesthetic, please add a [FYI] …
=> Seed initial client

src/core/mod.rs, src/core/operation_handler.rs, src/core/request_handler.rs
This commit makes the attributes within the request and operation
handlers configurable through the `CoreClient`.
fixes #3
=> Make inner attributes configurable

CONTRIBUTING.md, README.md, src/auth.rs, src/core/mod.rs, src/core/operation_handler.rs, src/core/request_handler.rs, src/error.rs, src/lib.rs, tests/ci.sh
This commit updates the way copyrights are displayed on files and adds
the Contributors file.
=> Update the way copyrights are displayed

Cargo.toml, README.md, src/core/mod.rs, src/core/operation_handler.rs, src/core/request_handler.rs, src/error.rs, src/lib.rs, src/tests/core_tests.rs, src/tests/mod.rs, tests/ci.sh
This commit creates the testing framework used to verify the client
library. It also adds unit tests for the operations implemented thus
far.
Will add more unit tests, this is just to verify the general soundness of the plan.
=> Add testing framework and unit tests

Cargo.toml, src/core/ipc_client/mod.rs, src/core/ipc_client/unix_socket.rs, src/core/mod.rs, src/core/request_handler.rs, src/core/testing/core_tests.rs, src/core/testing/mod.rs, src/lib.rs, src/tests/mod.rs
This commit moves IPC functionality into its own module, allowing the
`RequestHandler` to be independent of the underlying communication
mechanism.
Fixes #13
=> Factor IPC handling out of the request handler

src/core/testing/core_tests.rs, src/core/testing/mod.rs
This commit adds a test for a failing IPC.
=> Add failing IPC test

Cargo.toml, src/core/mod.rs, src/core/operation_handler.rs, src/core/request_handler.rs, src/core/testing/core_tests.rs, src/lib.rs
This commit adds more thorough documentation to the crate, as well as
code examples for using the `CoreClient`.
=> Add documentation

src/core/mod.rs, src/core/testing/core_tests.rs
This commit adds the "psa_" prefix to PSA-related methods on the
CoreClient. This makes it more clear that these are direct mappings to
the operations represented in the IPC contract.
=> Add "psa_" prefix to method names.

src/core/basic_client.rs, src/core/testing/core_tests.rs, src/core/testing/mod.rs, src/error.rs
This commit makes the `implicit_provider` optional, allowing the
`BasicClient` to start with no such provider. When in this state, core
operations are allowed but crypto operations will fail with
`NoProvider`.
=> Make `implicit_provider` optional

src/core/ipc_handler/mod.rs, src/core/ipc_handler/unix_socket.rs, src/core/request_client.rs, src/core/testing/mod.rs
This commit adds functionality to the `BasicClient` to update the
timeout of IPC handlers in flight.
=> Add methods for modifying timeout of IPC handlers

Cargo.toml, src/core/basic_client.rs, src/core/mod.rs, src/core/testing/core_tests.rs
This commit updates the `core` module to resurface the whole parsec
interface, making it easier for clients to access the same version of
the interface as used in the client internals.
=> Resurface full interface as part of core

Cargo.toml, src/core/operation_client.rs, src/core/request_client.rs
This change allows the BasicClient and references to it to be shared
amoung threads.
=> Add Send and Sync to trait objects

Cargo.toml, src/core/basic_client.rs
The export_public_key operation is even available if the export flag is
set to false. This flag is only for exporting the full key (private and
public parts).
=> Bump version number and fix comment

Cargo.toml, src/auth.rs, src/core/basic_client.rs, src/core/mod.rs, src/core/testing/core_tests.rs, src/core/testing/mod.rs
This commit improves the security of the library by wiping out all
sensitive data before it is dropped.
=> Add memory wiping functionality

Cargo.toml, README.md, src/core/ipc_handler/unix_socket.rs
Adds a check for the directory containing the socket. It must be owned
by the parsec user and parsec-clients group and be 750. This check is
disabled for testing.
=> Change socket location and add checks

Cargo.toml, src/core/basic_client.rs, src/core/testing/core_tests.rs
=> Added asymmetric encrypt and decrypt

src/error.rs
No issue for this. This is required for decent error handling for the work going on for [this issue](https://github.com/parallaxsecond/parsec/issues/202).
=> Implement `Error` and `Display` traits for `parsec_client::error::Error`

.github/workflows/nightly.yml, Cargo.toml, README.md, src/core/basic_client.rs, src/core/testing/core_tests.rs
Also uses Uuid from the interface, removes the license notices for
crates we use in the README.md and adds a nightly workflow.
=> Upgrade dependencies versions

src/core/basic_client.rs, src/core/ipc_handler/unix_socket.rs
See [this issue](https://github.com/parallaxsecond/parsec/issues/250) for details.
=> Update the socket path to new location

Cargo.toml, src/core/basic_client.rs, src/core/testing/core_tests.rs
Rust client support for the `ListKeys` operation.
=> Add ListKeys support

Cargo.toml
Signed-off-by: Joe Ellis <joe.ellis@arm.com>
=> Quickfix: replace parsec-interface patch with a direct dependency

Cargo.toml, README.md, src/core/ipc_handler/unix_socket.rs, src/error.rs
This commit removes the filesystem checks for correct permissions on
Parsec "assets". The checks can now be removed because the new locations
in the filesystem mean that only a privileged user can create the files.
Fixes #51
=> Remove filesystem checks

src/auth.rs, src/core/testing/core_tests.rs
This commit adds support for authentication using Unix Peer Credentials.
This involves the library automatically populating the `Auth` field of
every request with a serialized version of the UID.
Closes #41
=> Add Unix Peer Credential auth support

src/auth.rs, src/core/basic_client.rs, src/core/operation_client.rs, src/core/testing/core_tests.rs, src/core/testing/mod.rs, src/error.rs
This commit implements bootstrapping of the `BasicClient`. Previously,
the client would be initialised without any implicit provider and
with a mandatory authentication value. Now the client can be initialised
with default values for both, with a conditional parameter required for
the case when direct authentication is in use.
=> Implement provider and auth bootstrapping

.travis.yml, Cargo.toml, src/auth.rs, src/core/basic_client.rs, src/core/operation_client.rs, src/core/testing/core_tests.rs, src/error.rs, tests/ci.sh
Using this method, the client will fetch its JWT-SVID and send it in the
authentication field.
The socket endpoint is found through the SPIFFE_ENDPOINT_SOCKET
environment variable.
=> Add a JWT-SVID authentication method

Cargo.toml
Signed-off-by: Paul Howard <paul.howard@arm.com>
=> Consume parsec-interface at 0.22.0 and bump crate to 0.12.0

Cargo.toml, src/core/basic_client.rs, src/core/testing/core_tests.rs
=> Add ListClients and DeleteClient operations

Cargo.toml, src/core/basic_client.rs, src/error.rs
=> Update interface dependency

Cargo.toml, src/core/basic_client.rs, src/core/ipc_handler/unix_socket.rs
Gives more time for operations executing on slower machines.
=> Increase the default timeout to 60 seconds

Cargo.toml, src/core/basic_client.rs, src/core/ipc_handler/mod.rs, src/core/ipc_handler/unix_socket.rs, src/core/operation_client.rs, src/core/request_client.rs, src/error.rs
This commit adds functionality to create a IPC connector from a URL and
to bootstrap the IPC handler creation from an environment variable using
this new functionality.
Fixes #37
=> Bootstrap socket location from env variable

README.md
=> Add documentation about the endpoint env. var.

src/core/basic_client.rs
That ensures that the parsec-tool does not show it by default.
=> Move a log message from info to debug

.github/workflows/nightly.yml, .gitignore, tests/coverage.sh
This commit adds code coverage checking for the tests in the repo to the
nightly Github Actions run.
=> Add code coverage checking to the nightly run

Cargo.toml, src/core/basic_client.rs, src/core/operation_client.rs, src/core/testing/core_tests.rs, src/core/testing/mod.rs
Add dependency on the newest (git only at the moment) parsec-interface with support for sign/verify message.
Plenty of transitions from 'ProviderID' to 'ProviderId'.
Few linter corrections in tests.
Signed-off-by: Robert Drazkowski <Robert.Drazkowski@globallogic.com>
=> Add dependency on the newest (git only at the moment) parsec-interface.

src/core/basic_client.rs, src/core/testing/core_tests.rs
There was a typo in a working (not yet pushed) copy of Parsec/e2e-tests making sign/verify_message tests always succeeding.
After the typo was corrected, it exposed the problem and below changes fix it.
=> Support for ps_sign_ and ps_verify_message Parsec operations.

Cargo.toml, README.md, src/auth.rs, src/core/basic_client.rs, src/error.rs, tests/ci.sh
As the number of dependencies introduced by the new crate is high, add
it as a separate feature.
The functionality is the same as the `spiffe` branch but with a released
crate named "spiffe".
**Note:**  the `spiffe` branch will be deleted when this PR is merged.
=> Add SPIFFE authentication via the new crate

Cargo.toml, README.md, src/core/basic_client.rs, src/core/testing/core_tests.rs
Also updates the code documention to be up to date.
=> Prepare for the release

Cargo.toml, src/core/basic_client.rs
Added the CanDoCrypto operation to the basic client by adding the can_do_crypto function to the implementation of BasicClient
Signed-off-by: Sam Davis <sam.davis@arm.com>
=> Added CanDoCrypto to basic client.

src/core/basic_client.rs
Tested internally with first e2e tests and works fine.
Signed-off-by: artur.kazimierski <artur.kazimierski@globallogic.com>
=> Add PsaCipherEncrypt and PsaCipherDecrypt operations

Cargo.toml
This change points to the `parsec-interface` revision, which includes the deprecated primitives' checks.
Relates to: https://github.com/parallaxsecond/parsec/issues/119 
Signed-off-by: Mohamed Omar Asaker <mohamed.omarasaker@arm.com>
=> Build parse-interface with deprecated primitive feature changes

src/lib.rs
This PR only removed const_err since it will be a hard error in future: https://github.com/rust-lang/rust/issues/71800
Signed-off-by: Marcus de Lima [marcus.lima@azion.com](mailto:marcus.lima@azion.com)
=> Update to remove const_err

Cargo.toml, src/auth.rs, src/core/testing/core_tests.rs
The 'users' crate is currently being flagged as unmaintained in https://rustsec.org/advisories/RUSTSEC-2023-0040.html .
It is currently only being used to get the uid of the user of a running process.
* Replace all users::get_current_uid() calls with libc::getuid() calls.
* Remove the users crate from Cargo.toml.
* Add libc to the Cargo.toml to call libc::getuid() instead.
Please refer to https://github.com/parallaxsecond/parsec/pull/684 for more information on this PR.
=> Remove unmaintained 'users' crate

.cargo/audit.toml, .github/workflows/ci.yml, .github/workflows/nightly.yml
https://github.com/parallaxsecond/parsec-client-rust/actions/runs/6419270620/job/17428760394
Issue is generated from spiffe, which will be upgraded post-release
=> .cargo/audit: Ignore unmaintained ansi_term util spiffe is upgraded

.github/workflows/nightly.yml
While the rest of the tests use actions/checkout@v2, coverage builds currently uses v1.
* Use actions/checkout@v2 instead of actions/checkout@v1
=> ci/nightly: use actions/checkoutv2 for coverage builds

.github/workflows/nightly.yml, tests/coverage.sh
This commit fixes nightly issues:
Certain tests ran by coverage.sh require a mock service to have started before the tests are actually ran.
* Clone and start the parsec-mock service for coverage testing.
=> ci/nightly: Run parsec-mock for coverage tests
