src/core/basic_client.rs
This commit adds getters for auth_data and implicit_provider to the
BasicClient.
=> Add getters for auth_data and implicit_provider

Cargo.toml, src/core/basic_client.rs, src/core/testing/core_tests.rs
=> Import the new interface

Cargo.toml
=> Import the newest interface and increase version

Cargo.toml, tests/ci.sh
Also adds feature testing on the CI.
=> Import the newer interface

src/core/ipc_handler/unix_socket.rs
The cfg gate was badly written.
=> Fix the fs check on the socket folder feature

Cargo.toml, src/core/basic_client.rs, src/core/testing/core_tests.rs
=> Added PsaExportKey

Cargo.toml
Adding the Error implementation as a patch version.
=> Publish a new version

Cargo.toml, src/core/basic_client.rs
Signed-off-by: Joe Ellis <joe.ellis@arm.com>
=> Add Rust client support for `psa_generate_random` operation

src/core/basic_client.rs, src/core/testing/core_tests.rs
=> Added aead encrypt and decrypt

src/core/basic_client.rs
Signed-off-by: Joe Ellis <joe.ellis@arm.com>
=> Add support for ListAuthenticators operation

src/core/basic_client.rs, src/core/testing/core_tests.rs
=> Added has compute and compare

src/core/basic_client.rs, src/core/testing/core_tests.rs
=> Added raw key agreement and test

src/core/basic_client.rs
=> Add a new construction for naked client

README.md
=> Add a note about JWT-SVID Workload Endpoint

Cargo.toml, README.md, src/auth.rs, src/core/basic_client.rs, src/error.rs
This will be pushed in its own branch, see
parallaxsecond/parsec#327
=> Remove spiffe-based feature from master

Cargo.toml, README.md, src/auth.rs, src/core/basic_client.rs, src/error.rs
This reverts commit 5e8702ff0b6b4c4930acf0193f6547e3419b2d38.
=> Revert "Remove spiffe-based feature from master"

Cargo.toml
=> Update hash to latest interface

Cargo.toml
Also updates the authors field.
=> Update the interface to latest master

CHANGELOG.md
=> Add the CHANGELOG

.cargo/audit.toml
Adding the same audit config file we use for the service.
=> Add cargo-audit config file.

README.md
=> Change Codecov badge to main branch

Cargo.toml
Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>
=> Use the main branch of Parsec-interface

src/core/basic_client.rs
This commit adds two methods for calling TPM-specific attestation
functionality based on the ActivateCredential mechanism.
We can always change this in the future if we decide we want to make the methods non-specific to the underlying mechanism.
=> Add activate credential attestation methods

Cargo.toml
=> Prepare for new version of client

Cargo.toml
Signed-off-by: Mohamed Omar Asaker <mohamed.omarasaker@arm.com>
=> Bump Crates' versions

CHANGELOG.md
Signed-off-by: Mohamed Omar Asaker <mohamed.omarasaker@arm.com>
=> Update changelog for the release

CHANGELOG.md, Cargo.toml
This MR adds the following changes:
- Bumps parsec interface crate
- Update crate version
- Add changelog
Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>
=> Bump parsec-interface and update crate version

Cargo.toml
Signed-off-by: Tomás González <tomasagustin.gonzalezorlando@arm.com>
=> Bump parsec-interface to 0.29.0

CHANGELOG.md, Cargo.toml
Signed-off-by: Tomás González <tomasagustin.gonzalezorlando@arm.com>
=> Bump crate version to 0.16.0 and update changelog
